name: ci

on:
  workflow_dispatch:
  schedule:
    - cron: '0 10 * * *' # everyday at 10am
  push:
    branches:
      - 'main'
      - 'releases/v*'
    tags:
      - 'v*'
  pull_request:

jobs:
  do:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        version:
          - latest
          - 0.2.232
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Dagger
        uses: ./
        with:
          version: ${{ matrix.version }}
          cmds: |
            project update
            do test
          workdir: ./test/ci

  args-deprecated:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Dagger
        uses: ./
        with:
          cmds: |
            project update
            do test
          workdir: ./test/ci

  install-only:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        version:
          - 0.2.232
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Dagger
        uses: ./
        with:
          version: ${{ matrix.version }}
          install-only: true
      -
        name: Check
        run: |
          dagger-cue version

  build-ref:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ref:
          - refs/heads/cue-sdk
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Dagger
        uses: ./
        with:
          version: https://github.com/dagger/dagger.git#${{ matrix.ref }}
          cmds: |
            project update
            do test
          workdir: ./test/ci
